<!-- My sql  -->

In [ ]:
import sqlite3
conn  = sqlite3.connect('manshi.db')
cursor = conn.cursor()

In [ ]:
cursor.execute(''' CREATE TABLE IF NOT EXISTS manshi(id INTEGER PRIMARY KEY AUTOINCREMENT, 
                   name TEXT NOT NULL,
                   age INTEGER,
                   grade TEXT
    )''')
conn.commit()
print("Table created successfully")

In [ ]:
def insert_student(name, age, grade):
    cursor.execute("INSERT INTO manshi (name, age, grade) VALUES (?, ?, ?)", (name, age, grade))
    conn.commit()
    print("Student inserted successfully.")


insert_student('Riya', 20, 'A')
insert_student('Divyank', 22, 'B')

In [ ]:
def fetch_students():
    cursor.execute("SELECT * FROM manshi")
    rows = cursor.fetchall()
    for row in rows:
        print(row)
fetch_students()

In [ ]:
def update_student(student_id, new_name, new_age, new_grade):
    cursor.execute("UPDATE manshi SET name=?, age=?, grade=? WHERE id=?", (new_name, new_age, new_grade, student_id))
    conn.commit()
    print("Student updated successfully.")
update_student(1, 'Riya Sharma', 21, 'A+')

In [ ]:
def delete_student(student_id):
    cursor.execute("DELETE FROM manshi WHERE id=?", (student_id,))
    conn.commit()
    print("Student deleted successfully.")
delete_student(2)


In [ ]:
conn.close()
print("Database connection closed.")

In [ ]:
# minor project

In [ ]:
import sqlite3

# Database connection
conn = sqlite3.connect("atm.db")
cur = conn.cursor()

# Table create (run once)
cur.execute('''
CREATE TABLE IF NOT EXISTS accounts (
    acc_no INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT,
    pin TEXT,
    balance REAL
)
''')
conn.commit()


In [ ]:
def create_account(name, pin, balance):
    cur.execute("INSERT INTO accounts (name, pin, balance) VALUES (?, ?, ?)", (name, pin, balance))
    conn.commit()
    print(" Account created successfully!")
# Example
# create_account("Divyank", "1234", 5000)

In [ ]:
def login(acc_no, pin):
    cur.execute("SELECT * FROM accounts WHERE acc_no=? AND pin=?", (acc_no, pin))
    user = cur.fetchone()
    if user:
        print(f" Welcome {user[1]}!")
        return user
    else:
        print(" Invalid account number or PIN.")
        return None


In [ ]:
def check_balance(acc_no):
    cur.execute("SELECT balance FROM accounts WHERE acc_no=?", (acc_no,))
    balance = cur.fetchone()[0]
    print(f"Current Balance: {balance}")

In [ ]:
def deposit(acc_no, amount):
    cur.execute("UPDATE accounts SET balance = balance + ? WHERE acc_no=?", (amount, acc_no))
    conn.commit()
    print(f" {amount} deposited successfully.")


In [ ]:
def withdraw(acc_no, amount):
    cur.execute("SELECT balance FROM accounts WHERE acc_no=?", (acc_no,))
    current_balance = cur.fetchone()[0]

    if amount > current_balance:
        print(" Insufficient balance!")
    else:
        cur.execute("UPDATE accounts SET balance = balance - ? WHERE acc_no=?", (amount, acc_no))
        conn.commit()
        print(f" {amount} withdrawn successfully.")

In [ ]:
def atm_menu():
    print("===== Welcome to Python ATM =====")
    acc_no = int(input("Enter Account Number: "))
    pin = input("Enter PIN: ")

    user = login(acc_no, pin)
    if not user:
        return

    while True:
        print("\n--- Menu ---")
        print("1. Check Balance")
        print("2. Deposit")
        print("3. Withdraw")
        print("4. Exit")
        choice = input("Enter your choice: ")

        if choice == '1':
            check_balance(acc_no)
        elif choice == '2':
            amt = float(input("Enter amount to deposit: "))
            deposit(acc_no, amt)
        elif choice == '3':
            amt = float(input("Enter amount to withdraw: "))
            withdraw(acc_no, amt)
        elif choice == '4':
            print(" Thank you for using the ATM. Bye!")
            break
        else:
            print("Invalid choice.")


In [ ]:
atm_menu()
conn.close()


In [1]:
# numpy

In [2]:
import numpy as np

In [4]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.size)
print(arr.ndim)
print(arr.dtype)

(2, 3)
6
2
int64


In [7]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [8]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1])
print(arr[1:4])

20
[20 30 40]


In [10]:
print(np.zeros((2, 3)))
print(np.ones((3, 3)))
print(np.eye(3, 3))
print(np.full((2, 2), 7))
print(np.arange(1, 10, 4))
print(np.linspace(1, 5, 4))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[7 7]
 [7 7]]
[1 5 9]
[1.         2.33333333 3.66666667 5.        ]


In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)
print(a * b)
print(a ** 2)
print(np.sqrt(a))
print(np.mean(a))

[5 7 9]
[ 4 10 18]
[1 4 9]
[1.         1.41421356 1.73205081]
2.0


In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(np.sum(arr))
print(np.min(arr))
print(np.max(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

21
1
6
[5 7 9]
[ 6 15]


In [13]:
arr = np.array([[1, 2], [3, 4]])
print(arr.flatten())

[1 2 3 4]


In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[2, 0], [1, 2]])
print(np.dot(a, b))

[[ 4  4]
 [10  8]]


In [17]:
# NumPy Coding Questions

In [19]:
# Create a NumPy array of integers from 0 to 10.
arr1 = np.arange(0, 11)
print("Array from 0 to 10:\n", arr1)

Array from 0 to 10:
 [ 0  1  2  3  4  5  6  7  8  9 10]


In [20]:
# Create an array of 10 zeros and change the 5th value to 1.
arr2 = np.zeros(10, dtype=int)
arr2[4] = 1     
print("\nArray of zeros with 5th element as 1:\n", arr2)


Array of zeros with 5th element as 1:
 [0 0 0 0 1 0 0 0 0 0]


In [21]:
# Generate an array of 10 ones.
arr3 = np.ones(10, dtype=int)
print("\nArray of 10 ones:\n", arr3)


Array of 10 ones:
 [1 1 1 1 1 1 1 1 1 1]


In [22]:
# Create a 1D array of 20 equally spaced numbers between 0 and 1.
arr4 = np.linspace(0, 1, 20)
print("\n20 equally spaced numbers between 0 and 1:\n", arr4)


20 equally spaced numbers between 0 and 1:
 [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [23]:
# Create a 3x3 identity matrix.
arr5 = np.eye(3)
print("\n3x3 Identity matrix:\n", arr5)


3x3 Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
# Create a 4x4 matrix with values from 0 to 15.
arr6 = np.arange(16).reshape(4,4)
print("\n4x4 matrix from 0 to 15:\n", arr6)


4x4 matrix from 0 to 15:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [25]:
# Generate a 5x5 matrix with random values.
arr7 = np.random.rand(5,5)
print("\n5x5 random matrix:\n", arr7)


5x5 random matrix:
 [[0.19528723 0.39753841 0.34696483 0.5134472  0.26943648]
 [0.80728625 0.09880178 0.25261875 0.06919043 0.34478798]
 [0.15585346 0.46768248 0.98959785 0.23791301 0.03570505]
 [0.71207398 0.81299674 0.21066318 0.91164883 0.37282805]
 [0.39508533 0.17496966 0.66828298 0.8659603  0.86443415]]


In [26]:
# Reverse the elements of an array.
arr8 = np.array([1,2,3,4,5])
reversed_arr8 = arr8[::-1]
print("\nReversed array:\n", reversed_arr8)


Reversed array:
 [5 4 3 2 1]


In [27]:
# Flatten a 2D array to 1D.
arr9 = np.array([[1,2],[3,4],[5,6]])
flattened_arr9 = arr9.flatten()
print("\nFlattened array:\n", flattened_arr9)


Flattened array:
 [1 2 3 4 5 6]


In [ ]:
# Extract even numbers from an array.
arr10 = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = arr10[arr10 % 2 == 0]
print("\nEven numbers from array:\n", even_numbers)